apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: web
  namespace: linkforge
spec:
  healthCheck:
    type: HTTP
    requestPath: /healthz
    port: 8080
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
  timeoutSec: 30
